name: "Auto DocGen LLM"
description: "Genera documentación con un LLM y actualiza un .docx"
inputs:
  openai_key:
    required: true
    description: "Tu clave de OpenAI (API KEY)"

runs:
  using: "composite"
  steps:
    - name: Instalar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependencias
      run: |
        pip install openai python-docx gitpython
      shell: bash

    - name: Ejecutar generador
      env:
        OPENAI_API_KEY: ${{ inputs.openai_key }}
      run: |
        python main.py
      shell: bash
